# defines:
#  
#  OPENCL_FOUND
#  OPENCL_INCLUDE_DIR
#  OPENCL_LIBRARIES
#

# win32 not yet supported

SET(OPENCL_FOUND "NO")

FIND_PATH(OPENCL_INCLUDE_DIR CL/cl.h ~/NVIDIA_GPU_Computing_SDK/OpenCL/common/inc/ )
FIND_LIBRARY(OPENCL_LIBRARIES OpenCL ENV LD_LIBRARY_PATH)

IF(OPENCL_LIBRARIES)
	SET(OPENCL_FOUND "YES")
ENDIF(OPENCL_LIBRARIES)

MARK_AS_ADVANCED(OPENCL_INCLUDE_DIR)
